import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@300;400;600;700&display=swap" rel="stylesheet"></link>
        <script src="https://kit.fontawesome.com/13f2849f05.js" crossorigin="anonymous"></script>
      </Head>
      <Navbar />
      <main className={styles.main}>
        
      </main>

      <Footer />
    </div>
  )
}
