import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function KienThucBDS() {
    return (
        <div>
            <Head>
                <title>Kiến thức bất động sản</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@300;400;600;700&display=swap" rel="stylesheet"></link>
                <script src="https://kit.fontawesome.com/13f2849f05.js" crossOrigin="anonymous"></script>
            </Head>
            <Navbar />
      <main className={styles.main}>
            <h1>Kiến Thức Bất Động Sản</h1>
      </main>

      <Footer />
        </div>
    )
}